### ISSUE TITLE
List all location data

### ISSUE THREAD

**Issue by DebbySchavl** [DebbySchavl/capstoneProject#2]
## User Strory
As a User, I want to see a List with all location data

## Description

![Image](https://user-images.githubusercontent.com/122889089/255880286-3da994ad-69ae-456a-8b28-27bc5af98ed6.png)

## Acceptance Criteria
- [ ]  List with all uploaded location data

## Tasks
- [ ]  add getAll and getById Endpoint
- [ ]  fetch get
- [ ]  show data in a list
