### ISSUE TITLE
Add delete button

### ISSUE THREAD

**Issue by DebbySchavl** [DebbySchavl/capstoneProject#4]
## User Story
As a user, I want to delete selected Data points

## Description

![Image](https://user-images.githubusercontent.com/122889089/255888750-2594b172-c7a3-4fd9-bad2-8376f729a78a.png)

## Acceptance Criteria
- [ ] user can delete a selected list item  
- [ ] user gets feedback after sucessfull editing a list item 

## Tasks
- [ ] add delete endpoint
- [ ] fetch delete
- [ ] feedback toast
